@startuml Диаграмма активности
|Домовладелец / Администратор промышленных помещений|
start
repeat :Просмотр списка отчетов;
backward :Возвращение к списку отчетов;
repeat while (Необходимо сформировать новый отчет?) is (Нет) not (Да)
    :Выбор типа отчета;
    :Настройка параметров отчета;
    |Система|
    :Формирование отчета;
    :Сбор данных с IoT-устройств;
    if (Данные получены?) then (да)
        :Отчет сформирован;
    else (нет)
        :Сообщение об ошибке;
        end
    endif
    |Домовладелец / Администратор промышленных помещений|
    :Отображение отчета о потреблении;
|Домовладелец / Администратор промышленных помещений|
:Простор отчета о потреблении;
if (Необходимо установить лимиты потребления электроэнергии?) then (да)
    :Настройка лимитов потребления;
    |Система|
    :Добавление лимитов потребления для устройства;
    :Настройка уведомлений о превышении потребления;
    |Домовладелец / Администратор промышленных помещений|
else (нет)  
endif    
stop
@enduml