@startuml C4_Context
title "Диаграмма контекста для системы учета энергопотребления"

!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml

Person(homeowner, "Домовладелец", "Мониторинг и анализ потребления электроэнергии")
Person(industrialFacilityAministrator, "Администраторы промышленных объектов", "Формирование отчетов о потреблении, оптимизация производственных процессов")
Person(electricCompany, "Электрокомпания", "Анализ данных о потреблении, формирование тарифов, планирование мощностей")
Person(technicalStaff, "Технический персонал", "Учет и обслуживание оборудования для мониторинга, решение технических проблем")

System(meteringSystem, "Система учета энергопотребления", "Мониторинг, анализ и отчетность по потреблению электроэнергии")

Rel(homeowner, meteringSystem, "Мониторинг энергопотребления", "HTTPS")
Rel(industrialFacilityAministrator, meteringSystem, "Мониторинг энергопотребления", "HTTPS")
Rel(electricCompany, meteringSystem, "Мониторинг энергопотребления", "HTTPS")
Rel(technicalStaff, meteringSystem, "Мониторинг энергопотребления", "HTTPS")

System_Ext(ioTDevices, "IoT-устройства", "Получение актуальных показаний счетчиков")
System_Ext(notificationService, "Сервис уведомлений", "Отправка уведомлений пользователям")
System_Ext(governmentServices, "Единый портал госуслуг (ЕПГУ)", "Интеграция с гос-ми сервисами")

Rel(meteringSystem, governmentServices, "Получение данных пользователей", "HTTPS/REST")
Rel(meteringSystem, ioTDevices, "Сбор данных с устройств", "MQTT/HTTP")
Rel(meteringSystem, notificationService, "Отправка уведомлений", "HTTPS/REST")


SHOW_FLOATING_LEGEND()

@enduml